#!/usr/bin/env python3
"""
Meeting Note Processor

When a new meeting note is pushed to 02-Meetings/:
1. Extracts action items
2. Structures the note with proper sections
3. Updates the relevant project MOC with new action items
"""

import os
import re
import yaml
from pathlib import Path
from datetime import datetime

VAULT_ROOT = Path(".")
MEETINGS_DIR = VAULT_ROOT / "02-Meetings"
MOCS_DIR = VAULT_ROOT / "04-MOCs"

def parse_frontmatter(content):
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            try:
                return yaml.safe_load(parts[1]), parts[2]
            except yaml.YAMLError:
                return {}, content
    return {}, content

def extract_action_items(body):
    action_items = []
    patterns = [
        r'[Aa]ction(?:\s*[Ii]tem)?[:\-]?\s*(.+)',
        r'[Tt][Oo][Dd][Oo][:\-]?\s*(.+)',
        r'[Tt]ask[:\-]?\s*(.+)',
        r'\- \[ \]\s*(.+)',
        r'•\s*(.+?)(?:\n|$)',
    ]
    
    for pattern in patterns:
        matches = re.findall(pattern, body)
        for match in matches:
            clean = match.strip()
            if clean and len(clean) > 5 and clean not in [a["task"] for a in action_items]:
                owner_match = re.search(r'[@\(]?([A-Z][a-z]+(?:\s[A-Z][a-z]+)?)[\)]?|\b(?:owner|assigned to|by)[:\s]+([A-Z][a-z]+(?:\s[A-Z][a-z]+)?)', clean)
                owner = owner_match.group(1) or owner_match.group(2) if owner_match else "TBD"
                action_items.append({
                    "task": clean,
                    "owner": owner if owner else "TBD",
                    "status": "pending",
                    "source": "meeting"
                })
    
    return action_items[:20]

def structure_meeting_note(note_path):
    content = note_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(content)
    
    if not fm:
        return False
    
    if fm.get("status") == "processed":
        return False
    
    action_items = extract_action_items(body)
    
    structured_body = f"""## Raw Notes
{body}

## Structured Summary
<!-- Auto-generated by GitHub Actions -->

### Key Discussion Points
<!-- Add key points here -->

### Decisions
- 

### Action Items
| Task | Owner | Status | Source |
|------|-------|--------|--------|
"""
    for item in action_items:
        structured_body += f"| {item['task']} | {item['owner']} | {item['status']} | {note_path.stem} |\n"
    
    structured_body += """
### Related Notes
- [[ ]]

---
*Processed by meeting-processor.yml on {date}*
""".format(date=datetime.now().strftime("%Y-%m-%d"))
    
    fm["status"] = "processed"
    fm["action-items-count"] = len(action_items)
    if action_items:
        fm["action-items"] = action_items
    
    new_content = "---\n" + yaml.dump(fm, sort_keys=False, allow_unicode=True) + "---" + structured_body
    note_path.write_text(new_content, encoding="utf-8")
    
    return action_items

def update_project_moc(project_name, action_items):
    moc_path = MOCS_DIR / f"{project_name}-MOC.md"
    if not moc_path.exists():
        return False
    
    content = moc_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(content)
    
    action_section = "\n## Action Items from Meetings\n"
    for item in action_items:
        action_section += f"- [ ] {item['task']} (Owner: {item['owner']}, Source: {item['source']})\n"
    
    if "## Action Items from Meetings" in body:
        body = body.replace("## Action Items from Meetings\n", "## Action Items from Meetings\n" + action_section.split("\n", 2)[2])
    else:
        body += action_section
    
    new_content = "---\n" + yaml.dump(fm, sort_keys=False, allow_unicode=True) + "---" + body
    moc_path.write_text(new_content, encoding="utf-8")
    return True

def main():
    changed = False
    
    for note_path in MEETINGS_DIR.glob("*.md"):
        if note_path.name == "README.md":
            continue
        
        action_items = structure_meeting_note(note_path)
        if action_items:
            changed = True
            print(f"Processed: {note_path.name} ({len(action_items)} action items)")
            
            content = note_path.read_text(encoding="utf-8")
            fm, _ = parse_frontmatter(content)
            project = fm.get("project")
            if project:
                updated = update_project_moc(project.replace(" ", "-").lower(), action_items)
                if updated:
                    print(f"  Updated MOC: {project}-MOC.md")
    
    if not changed:
        print("No new meeting notes to process.")

if __name__ == "__main__":
    main()
